# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Gold
description: > # this means to ignore newlines until "baseurl:"
  A podcast about design and productâ€”what it takes to create great experiences, and what happens when critical details are ignored, overlooked, or misunderstood.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://designgold.xyz" # the base hostname & protocol for your site
rehan-url: https://rehanbutt.com
lily-url: https://lilysamuels.com
jonathan-url: https://jonnycal.com

twitter: https://x.com/designgoldmedia
instagram: https://www.instagram.com/designgoldmedia/
threads: https://www.threads.com/@designgoldmedia

version: 3.0.1
# Build settings
markdown: kramdown

sass:
  style: compressed