# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Gold
description: > # this means to ignore newlines until "baseurl:"
  A podcast about all things design and technology, how we can create better experiences and the pitfall of things not considered or overlooked.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://designgold.xyz" # the base hostname & protocol for your site
rehan-url: https://rehanbutt.com
lily-url: https://lilysamuels.com
version: 3.0
# Build settings
markdown: kramdown

sass:
  style: compressed